# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clearance',
            field=models.BooleanField(default=False),
        ),
    ]
