# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_clearance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='clearance',
        ),
    ]
